// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupData(arg1) {
  return window['go']['main']['App']['BackupData'](arg1);
}

export function BatchAddSkillTags(arg1, arg2) {
  return window['go']['main']['App']['BatchAddSkillTags'](arg1, arg2);
}

export function BatchAddTags(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTags'](arg1, arg2);
}

export function BatchDeletePrompts(arg1) {
  return window['go']['main']['App']['BatchDeletePrompts'](arg1);
}

export function BatchDeleteSkills(arg1, arg2) {
  return window['go']['main']['App']['BatchDeleteSkills'](arg1, arg2);
}

export function BatchImportSkills(arg1) {
  return window['go']['main']['App']['BatchImportSkills'](arg1);
}

export function BatchRemoveSkillTags(arg1, arg2) {
  return window['go']['main']['App']['BatchRemoveSkillTags'](arg1, arg2);
}

export function BatchRemoveTags(arg1, arg2) {
  return window['go']['main']['App']['BatchRemoveTags'](arg1, arg2);
}

export function BatchSetPin(arg1, arg2) {
  return window['go']['main']['App']['BatchSetPin'](arg1, arg2);
}

export function BatchSetPinSkill(arg1, arg2) {
  return window['go']['main']['App']['BatchSetPinSkill'](arg1, arg2);
}

export function BatchUpdateCategory(arg1, arg2) {
  return window['go']['main']['App']['BatchUpdateCategory'](arg1, arg2);
}

export function CancelAIGeneration() {
  return window['go']['main']['App']['CancelAIGeneration']();
}

export function CleanupOrphanSkills() {
  return window['go']['main']['App']['CleanupOrphanSkills']();
}

export function CountPrompts() {
  return window['go']['main']['App']['CountPrompts']();
}

export function CountSkills() {
  return window['go']['main']['App']['CountSkills']();
}

export function CreatePrompt(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSkill'](arg1, arg2, arg3);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeleteSkill(arg1, arg2) {
  return window['go']['main']['App']['DeleteSkill'](arg1, arg2);
}

export function ExportPrompts(arg1, arg2) {
  return window['go']['main']['App']['ExportPrompts'](arg1, arg2);
}

export function ExportSkill(arg1, arg2) {
  return window['go']['main']['App']['ExportSkill'](arg1, arg2);
}

export function ExportSkills(arg1, arg2) {
  return window['go']['main']['App']['ExportSkills'](arg1, arg2);
}

export function GeneratePrompt(arg1) {
  return window['go']['main']['App']['GeneratePrompt'](arg1);
}

export function GetAIModels() {
  return window['go']['main']['App']['GetAIModels']();
}

export function GetAppHome() {
  return window['go']['main']['App']['GetAppHome']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetDataStats() {
  return window['go']['main']['App']['GetDataStats']();
}

export function GetLogLevel() {
  return window['go']['main']['App']['GetLogLevel']();
}

export function GetOrphanSkills() {
  return window['go']['main']['App']['GetOrphanSkills']();
}

export function GetPinnedPrompts(arg1) {
  return window['go']['main']['App']['GetPinnedPrompts'](arg1);
}

export function GetPinnedSkills(arg1) {
  return window['go']['main']['App']['GetPinnedSkills'](arg1);
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetPrompts(arg1, arg2) {
  return window['go']['main']['App']['GetPrompts'](arg1, arg2);
}

export function GetRecentPrompts(arg1) {
  return window['go']['main']['App']['GetRecentPrompts'](arg1);
}

export function GetRecentSkills(arg1) {
  return window['go']['main']['App']['GetRecentSkills'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkill(arg1) {
  return window['go']['main']['App']['GetSkill'](arg1);
}

export function GetSkills(arg1) {
  return window['go']['main']['App']['GetSkills'](arg1);
}

export function GetSystemFonts() {
  return window['go']['main']['App']['GetSystemFonts']();
}

export function GetTopUsedPrompts(arg1) {
  return window['go']['main']['App']['GetTopUsedPrompts'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportPrompts(arg1) {
  return window['go']['main']['App']['ImportPrompts'](arg1);
}

export function ImportSkill(arg1) {
  return window['go']['main']['App']['ImportSkill'](arg1);
}

export function ImportSkillAuto(arg1) {
  return window['go']['main']['App']['ImportSkillAuto'](arg1);
}

export function IncrementPromptUsage(arg1) {
  return window['go']['main']['App']['IncrementPromptUsage'](arg1);
}

export function ListSkillFiles(arg1) {
  return window['go']['main']['App']['ListSkillFiles'](arg1);
}

export function OpenDataDirectory() {
  return window['go']['main']['App']['OpenDataDirectory']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenJSONFileDialog() {
  return window['go']['main']['App']['OpenJSONFileDialog']();
}

export function OpenMultiZIPFileDialog() {
  return window['go']['main']['App']['OpenMultiZIPFileDialog']();
}

export function OpenZIPFileDialog() {
  return window['go']['main']['App']['OpenZIPFileDialog']();
}

export function OptimizeDescription(arg1) {
  return window['go']['main']['App']['OptimizeDescription'](arg1);
}

export function OptimizeName(arg1) {
  return window['go']['main']['App']['OptimizeName'](arg1);
}

export function OptimizePrompt(arg1) {
  return window['go']['main']['App']['OptimizePrompt'](arg1);
}

export function QuickBackup() {
  return window['go']['main']['App']['QuickBackup']();
}

export function QuickBackupInfo() {
  return window['go']['main']['App']['QuickBackupInfo']();
}

export function QuickRestore() {
  return window['go']['main']['App']['QuickRestore']();
}

export function ResetAllData() {
  return window['go']['main']['App']['ResetAllData']();
}

export function RestoreData(arg1) {
  return window['go']['main']['App']['RestoreData'](arg1);
}

export function RevealInExplorer(arg1) {
  return window['go']['main']['App']['RevealInExplorer'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveJSONFileDialog(arg1) {
  return window['go']['main']['App']['SaveJSONFileDialog'](arg1);
}

export function SaveZIPFileDialog(arg1) {
  return window['go']['main']['App']['SaveZIPFileDialog'](arg1);
}

export function SelectDirectoryDialog() {
  return window['go']['main']['App']['SelectDirectoryDialog']();
}

export function SetAppHome(arg1) {
  return window['go']['main']['App']['SetAppHome'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function TestAIConnection(arg1, arg2) {
  return window['go']['main']['App']['TestAIConnection'](arg1, arg2);
}

export function TogglePinPrompt(arg1) {
  return window['go']['main']['App']['TogglePinPrompt'](arg1);
}

export function TogglePinSkill(arg1) {
  return window['go']['main']['App']['TogglePinSkill'](arg1);
}

export function TranslateContent(arg1, arg2) {
  return window['go']['main']['App']['TranslateContent'](arg1, arg2);
}

export function UpdatePrompt(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2, arg3, arg4);
}
