// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchDeletePrompts(arg1) {
  return window['go']['main']['App']['BatchDeletePrompts'](arg1);
}

export function BatchDeleteSkills(arg1, arg2) {
  return window['go']['main']['App']['BatchDeleteSkills'](arg1, arg2);
}

export function BatchImportSkills(arg1) {
  return window['go']['main']['App']['BatchImportSkills'](arg1);
}

export function CountPrompts() {
  return window['go']['main']['App']['CountPrompts']();
}

export function CountSkills() {
  return window['go']['main']['App']['CountSkills']();
}

export function CreatePrompt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePrompt'](arg1, arg2, arg3, arg4);
}

export function CreateSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSkill'](arg1, arg2, arg3);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeleteSkill(arg1, arg2) {
  return window['go']['main']['App']['DeleteSkill'](arg1, arg2);
}

export function ExportPrompts(arg1, arg2) {
  return window['go']['main']['App']['ExportPrompts'](arg1, arg2);
}

export function ExportSkill(arg1, arg2) {
  return window['go']['main']['App']['ExportSkill'](arg1, arg2);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetPrompts(arg1, arg2) {
  return window['go']['main']['App']['GetPrompts'](arg1, arg2);
}

export function GetRecentPrompts(arg1) {
  return window['go']['main']['App']['GetRecentPrompts'](arg1);
}

export function GetRecentSkills(arg1) {
  return window['go']['main']['App']['GetRecentSkills'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkill(arg1) {
  return window['go']['main']['App']['GetSkill'](arg1);
}

export function GetSkillStoragePath() {
  return window['go']['main']['App']['GetSkillStoragePath']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function ImportPrompts(arg1) {
  return window['go']['main']['App']['ImportPrompts'](arg1);
}

export function ImportSkill(arg1) {
  return window['go']['main']['App']['ImportSkill'](arg1);
}

export function ListSkillFiles(arg1) {
  return window['go']['main']['App']['ListSkillFiles'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenJSONFileDialog() {
  return window['go']['main']['App']['OpenJSONFileDialog']();
}

export function OpenMultiZIPFileDialog() {
  return window['go']['main']['App']['OpenMultiZIPFileDialog']();
}

export function OpenZIPFileDialog() {
  return window['go']['main']['App']['OpenZIPFileDialog']();
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveJSONFileDialog(arg1) {
  return window['go']['main']['App']['SaveJSONFileDialog'](arg1);
}

export function SaveZIPFileDialog(arg1) {
  return window['go']['main']['App']['SaveZIPFileDialog'](arg1);
}

export function SelectDirectoryDialog() {
  return window['go']['main']['App']['SelectDirectoryDialog']();
}

export function UpdatePrompt(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdatePrompt'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2, arg3, arg4);
}
