// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {handler} from '../models';
import {utils} from '../models';

export function BackupData(arg1:string):Promise<void>;

export function BatchDeletePrompts(arg1:Array<number>):Promise<number>;

export function BatchDeleteSkills(arg1:Array<number>,arg2:boolean):Promise<number>;

export function BatchImportSkills(arg1:Array<string>):Promise<db.ImportResult>;

export function CleanupOrphanSkills():Promise<number>;

export function CountPrompts():Promise<number>;

export function CountSkills():Promise<number>;

export function CreatePrompt(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:boolean):Promise<db.Prompt>;

export function CreateSkill(arg1:string,arg2:string,arg3:Array<string>):Promise<db.Skill>;

export function DeletePrompt(arg1:number):Promise<void>;

export function DeleteSkill(arg1:number,arg2:boolean):Promise<void>;

export function ExportPrompts(arg1:Array<number>,arg2:string):Promise<void>;

export function ExportSkill(arg1:number,arg2:string):Promise<void>;

export function ExportSkills(arg1:Array<number>,arg2:string):Promise<void>;

export function GetAppHome():Promise<string>;

export function GetCategories():Promise<Array<string>>;

export function GetDataStats():Promise<handler.DataStats>;

export function GetOrphanSkills():Promise<Array<db.Skill>>;

export function GetPinnedPrompts(arg1:number):Promise<Array<db.Prompt>>;

export function GetPinnedSkills(arg1:number):Promise<Array<db.Skill>>;

export function GetPrompt(arg1:number):Promise<db.Prompt>;

export function GetPrompts(arg1:string,arg2:string):Promise<Array<db.Prompt>>;

export function GetRecentPrompts(arg1:number):Promise<Array<db.Prompt>>;

export function GetRecentSkills(arg1:number):Promise<Array<db.Skill>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSkill(arg1:number):Promise<db.Skill>;

export function GetSkills(arg1:string):Promise<Array<db.Skill>>;

export function GetSystemFonts():Promise<Array<string>>;

export function GetTopUsedPrompts(arg1:number):Promise<Array<db.Prompt>>;

export function GetVersion():Promise<Record<string, string>>;

export function ImportPrompts(arg1:string):Promise<db.ImportResult>;

export function ImportSkill(arg1:string):Promise<db.Skill>;

export function ImportSkillAuto(arg1:string):Promise<db.ImportResult>;

export function IncrementPromptUsage(arg1:number):Promise<void>;

export function ListSkillFiles(arg1:number):Promise<Array<db.SkillFile>>;

export function OpenDataDirectory():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function OpenJSONFileDialog():Promise<string>;

export function OpenMultiZIPFileDialog():Promise<Array<string>>;

export function OpenZIPFileDialog():Promise<string>;

export function QuickBackup():Promise<void>;

export function QuickBackupInfo():Promise<Record<string, any>>;

export function QuickRestore():Promise<utils.BackupRestoreResult>;

export function ResetAllData():Promise<Record<string, number>>;

export function RestoreData(arg1:string):Promise<utils.BackupRestoreResult>;

export function RevealInExplorer(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveJSONFileDialog(arg1:string):Promise<string>;

export function SaveZIPFileDialog(arg1:string):Promise<string>;

export function SelectDirectoryDialog():Promise<string>;

export function SetAppHome(arg1:string):Promise<void>;

export function TogglePinPrompt(arg1:number):Promise<void>;

export function TogglePinSkill(arg1:number):Promise<void>;

export function UpdatePrompt(arg1:number,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:boolean):Promise<void>;

export function UpdateSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateSettings(arg1:Record<string, string>):Promise<void>;

export function UpdateSkill(arg1:number,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;
